# 基本イメージの指定
FROM jupyter/base-notebook

# 作業ディレクトリの設定を /workspace に変更
WORKDIR /workspace

# environment.ymlをコンテナにコピー（コピー先のパスも変更）
COPY environment.yml /workspace/environment.yml

# Conda環境の作成
RUN conda env create -f /workspace/environment.yml

# Conda環境をアクティベートするための新しいRUNコマンド
RUN echo "source activate logo" > ~/.bashrc
ENV PATH /opt/conda/envs/logo/bin:$PATH

# Conda環境をJupyterカーネルとして登録
RUN /bin/bash -c "source /opt/conda/etc/profile.d/conda.sh && \
    conda activate logo && \
    python -m ipykernel install --user --name logo --display-name 'Python (logo)'"
#docker run --gpus all -p 8888:8888 -v /home/fumiya/Working/logo:/workspace jupyter_logo